### ISSUE TITLE
SwiftLint Rule 조사

### ISSUE THREAD

**Issue by 8k4058** [K890/Stock#12]
### Enable
* anyobject_protocol
* attributes
* class_delegate_protocol
* closing_brace
* closure_body_length
* closure_end_indentation
* closure_parameter_position
* closure_spacing
* colon
* comma
* control_statement
* contains_over_first_not_nil
* discouraged_optional_boolean
* discouraged_optional_collection
* dynamic_inline
* empty_count
* empty_parentheses_with_trailing_closure
* empty_string
* empty_xctest_method
* explicit_enum_raw_value
* explicit_self
* explicit_type_interface
* fatal_error_message
* file_length
* file_name
* first_where
* for_where
* force_cast
* force_try
* force_unwrapping
* function_body_length
* function_default_parameter_at_end
* function_parameter_count
* generic_type_name
* identical_operands
* identifier_name
* implicit_getter
* implicit_return
* implicitly_unwrapped_optional
* is_disjoint
* joined_default_parameter
* large_tuple
* leading_whitespace
* legacy_cggeometry_functions
* legacy_constant
* legacy_constructor
* legacy_nsgeometry_functions
* legacy_random
* let_var_whitespace
* line_length
* literal_expression_end_indentation
* mark
* modifier_order
* multiline_arguments
* multiline_function_chains
* multiline_parameters
* multiple_closures_with_trailing_closure
* no_grouping_extension
* notification_center_detachment
* object_literal
* opening_brace
* operator_usage_whitespace
* operator_whitespace
* overridden_super_call
* override_in_extension
* prefixed_toplevel_constant
* private_action
* private_over_fileprivate
* protocol_property_accessors_order
* redundant_discardable_let
* redundant_nil_coalescing
* redundant_optional_initialization
* redundant_set_access_control
* redundant_string_enum_value
* redundant_void_return
* return_arrow_whitespace
* shorthand_operator
* sorted_first_last
* sorted_imports
* statement_position
* static_operator
* strict_fileprivate
* switch_case_alignment
* switch_case_on_newline
* syntactic_sugar
* toggle_bool
* trailing_closure
* trailing_comma
* trailing_newline
* trailing_semicolon
* trailing_whitespace
* type_name
* unneeded_break_in_switch
* unneeded_parentheses_in_closure_argument
* untyped_error_in_catch
* unused_enumerated
* unused_import
* unused_optional_binding
* unused_private_declaration
* vertical_parameter_alignment
* vertical_parameter_alignment_on_call
* vertical_whitespace
* void_return
* weak_delegate
* xctfail_message
* yoda_condition
* collection_alignment
* conditional_returns_on_newline
* discouraged_object_literal
* number_separator
* fallthrough

### I don't know
* block_based_kvo
* compiler_protocol_init
* convenience_type
* discarded_notification_center_observer
* empty_enum_arguments
* explicit_acl
* explicit_init
* explicit_top_level_acl
* extension_access_modifier
* file_header
* inert_defer
* lower_acl_than_parent
* missing_docs
* nesting
* nimble_operator
* no_extension_access_modifier
* no_fallthrough_only
* pattern_matching_keywords
* private_unit_test
* prohibited_interface_builder
* prohibited_super_call
* quick_discouraged_call
* quick_discouraged_focused_test
* quick_discouraged_pending_test
* redundant_type_annotation
* required_enum_case
* single_test_class
* superfluous_disable_command
* todo
* type_body_length
* unavailable_function
* valid_ibinspectable
* array_init

**Comment by 8k4058** [comment]
@hkkkkkkkds 추가조사 후 프로젝트 적용 부탁드립니다.

**Comment by hkkkkkkkds** [comment]
본문에 작성된 [Rules](https://github.com/realm/SwiftLint/blob/master/Rules.md) 에서 사용 가능한 규칙들을 볼 수 있음.

모든 내용을 정리하기에는 양이 너무 많아 별도로 정리하지 않음.
위에 조사한 내용은 태헌님이 선정한 주관적 규칙으로서 프로젝트에 반영하지 않음.

프로젝트에 적용한 규칙들은 3차 정기 회의에서 결정하여 [SwiftLint Rules](https://github.com/K890/Stock/wiki/SwiftLint-Rules) 에 작성할 예정.

**Comment by hkkkkkkkds** [comment]
SwiftLint Rule 조사 완료되어 close 합니다.
project 내 SwiftLint 적용 및 규칙 선정은 별도 issue/wiki 로 관리하겠습니다.
